function [outputArg1,outputArg2] = Scenario2(scenarioParams)
%SCENARIO2 
% cocurrent followed by counter current 
params = [scenarioParams.Ca0; ...
    scenarioParams.Cb0;...
    scenarioParams.volumetricFlowRateFeed;...
    scenarioParams.Fa0; ...
    scenarioParams.Cps;...
    scenarioParams.Ua; ...
    scenarioParams.mDotCp; ...
    scenarioParams.Cpcool; ...
    scenarioParams.T0_k ; ...
    scenarioParams.T0_Kc ;...
    scenarioParams.k0;...
    scenarioParams.Kc0; ...
    scenarioParams.dHrxn ;...
    scenarioParams.E;...
    scenarioParams.R];

[VOut_1,Output_PFR1]=ode45(@(V,X)ODE_CoCurrentPFR(V,X,params), ...
scenarioParams.VSpan,[scenarioParams.X0;scenarioParams.T0;scenarioParams.Ta0]);

X_PFR1 = Output_PFR1(:,1);
T_PFR1 = Output_PFR1(:,2);
Ta_PFR1 = Output_PFR1(:,3);

X2 = X_PFR1(101);
T2 = T_PFR1(101);
Ta2 = Ta_PFR1(101);

X3 = X3_iterator;
Ca3 = scenarioParams.Ca0*(1-X3);
Cb3 = Ca3;
Fa3 = scenarioParams.Fa0*(1-X3);
Ta3 = Ta2;


params = [Ca3 ;
    Cb3 ;  ...
    scenarioParams.volumetricFlowRateFeed; ...
    Fa3;...
    scenarioParams.Cps;...
    scenarioParams.Ua; ...
    scenarioParams.mDotCp ;...
    scenarioParams.Cpcool; ...
    scenarioParams.T0_k ;...
    scenarioParams.T0_Kc ;...
    scenarioParams.k0;...
    scenarioParams.Kc0; ...
    scenarioParams.dHrxn ;...
    scenarioParams.E;...
    scenarioParams.R];
[VOut_2,Output_PFR2]=ode45(@(V,X)ODE_CoCurrentPFR(V,X,params),scenarioParams.VSpan,[X3;T3;Ta3]);


X_PFR2 = Output_PFR2(:,1);
T_PFR2 = Output_PFR2(:,2);
Ta_PFR2 = Output_PFR2(:,3);

X4 = X_PFR2(101);
T4 = T_PFR2(101);
Ta4 = Ta_PFR2(101);

subplot(4,1,1);
plot(scenarioParams.VSpan, X_PFR1);
xlabel('Volume');
ylabel('conversion');
title('conversion pfr1 cocurrent');

subplot(4,1,2);
plot(scenarioParams.VSpan, T_PFR1, scenarioParams.VSpan, Ta_PFR1);
xlabel('Volume');
ylabel('Temperature');
legend('T','Ta');
title('temperature pfr1 cocurrent');

subplot(4,1,3);
plot(scenarioParams.VSpan, X_PFR2);
xlabel('Volume');
ylabel('conversion');
title('conversion pfr2 cocurrent');

subplot(4,1,4);
plot(scenarioParams.VSpan, T_PFR2, scenarioParams.VSpan, Ta_PFR2);
xlabel('Volume');
ylabel('Temperature');
legend('T','Ta')
title('temperature pfr2 cocurrent');

end
